### ISSUE TITLE
Error de reflection al acceder a un producto que no es tuyo.

### ISSUE THREAD

**Issue by jxtaaa** [Altair-Bueno/ubay-spring#2]
Request processing failed; nested exception is org.springframework.orm.jpa.JpaSystemException: Could not set field value [14] value by reflection : [class uma.taw.ubayspring.entity.BidEntity.product] setter of uma.taw.ubayspring.entity.BidEntity.product; nested exception is org.hibernate.PropertyAccessException: Could not set field value [14] value by reflection : [class uma.taw.ubayspring.entity.BidEntity.product] setter of uma.taw.ubayspring.entity.BidEntity.product

**Comment by Altair-Bueno** [comment]
Done

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/67512202/170539219-19b07446-bcb3-47b3-a0df-8bcbe9402b21.png">
