### ISSUE TITLE
Exception when resetting password being an admin

### ISSUE THREAD

**Issue by jxtaaa** [Altair-Bueno/ubay-spring#21]
Request processing failed; nested exception is org.springframework.dao.InvalidDataAccessApiUsageException: The given id must not be null!; nested exception is java.lang.IllegalArgumentException: The given id must not be null!

**Comment by Altair-Bueno** [comment]
`/users/passwordChangeLink` generates an invalid link. Valid links look like this: `/auth/resetPassword?loginID=1&requestID=5rqpu7k2c2f55quxnb9e`

More information: https://github.com/Altair-Bueno/ubay-spring/blob/04cf11c14ee2978402655c8da35448b322fd12a3/src/main/java/uma/taw/ubayspring/dto/auth/ResetPasswordDTO.java#L16-L17
