### ISSUE TITLE
Error de reflection al añadir una categoría a favoritos.

### ISSUE THREAD

**Issue by jxtaaa** [Altair-Bueno/ubay-spring#3]
Request processing failed; nested exception is org.springframework.orm.jpa.JpaSystemException: Could not set field value [uma.taw.ubayspring.entity.ClientEntity@ba91c8aa] value by reflection : [class uma.taw.ubayspring.entity.UserFavouritesEntityPK.client] setter of uma.taw.ubayspring.entity.UserFavouritesEntityPK.client; nested exception is org.hibernate.PropertyAccessException: Could not set field value [uma.taw.ubayspring.entity.ClientEntity@ba91c8aa] value by reflection : [class uma.taw.ubayspring.entity.UserFavouritesEntityPK.client] setter of uma.taw.ubayspring.entity.UserFavouritesEntityPK.client

**Comment by Altair-Bueno** [comment]
Solved

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/67512202/170539589-6ffecb81-9d22-4aa7-b8e2-8d49412d0e3f.png">
